Stop intaking if note passed intake
team401/2024-Robot-Code pull request #159
Opened 2024-03-09 22:31 UTC by minhnguyenbhs

I'm not sure if this will work and it's definitely not robot tested; I can adjust numbers or switch the off condition from the current timer to checking for belt current if needed?
Was this what you were looking for?

2024-03-10 04:42 UTC, redPlover requested changes
Some changes requested, but looks good otherwise

2024-03-10 04:42 UTC, redPlover commented on src/main/java/frc/robot/subsystems/intake/IntakeIO.java
> +    public default boolean checkIfStopIntake() {
Could we please make this an input instead of a getter method?

2024-03-10 04:42 UTC, redPlover commented on src/main/java/frc/robot/subsystems/intake/IntakeSubsystem.java
> +            io.setBeltVoltage(IntakeConstants.beltPower);
We don't want to stop running the belt motor here.

2024-03-10 04:42 UTC, redPlover commented on src/main/java/frc/robot/subsystems/intake/IntakeIOSparkMax.java
> +    public boolean checkIfStopIntake() {
We're going to add a ToF sensor here so we can use that instead of current sensing and a timer.

2024-03-11 22:23 UTC, minhnguyenbhs commented
deleting pull request, jack's already doing it haha

2024-03-11 23:14 UTC, closed without merging

2024-03-11 23:14 UTC, linglejack06 commented
Addressed in PR #155