changed neo to talon
team401/2024-Robot-Code pull request #204
Opened 2024-10-09 22:30 UTC by minhnguyenbhs

I switched the CAN Spark Max intake motors to FalconFXs; is there anything else that needs to be changed?

2024-10-10 13:24 UTC, aidnem approved these changes
As long as updating the vendordeps is fine (I'll take your word for it), this looks good to me.

2024-10-10 13:24 UTC, aidnem commented on vendordeps/AdvantageKit.json
I assume updating vendordeps is fine and doesn't break anything?

2024-10-10 14:00 UTC, jkleiber commented
This looks good - let's test it on the robot before merging

2024-10-13 15:47 UTC, jkleiber requested changes
Please revert all vendor dep updates unless required for the change

2024-10-13 15:47 UTC, jkleiber commented on vendordeps/photonlib.json
Changes to this file result in code crash. Let's revert all vendor dependency upgrades that are not needed for this change

2024-10-17 17:22 UTC, jkleiber approved these changes
approved and will merge now

2024-10-17 17:22 UTC, merged